In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error as mse, mean_absolute_error as mae
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import seaborn as sns
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

## Legend
## Slava's glass. Pt. 2

The safe clicked open with a satisfying sound, almost like it knew Slava was not just any thief, but the one who came for his treasure.

He pulled out his glass. The real one. Warm. Intact.
For a moment, everything felt right. "This is it," he thought to himself, but then, the familiar, haunting voice of the mansion's security system echoed:

"What if I told you, this isn't what it seems?"
Slava shook his head, pushing the strange thought away, but that ominous question lingered in his mind.

He pulled out his phone to call a taxi — and realized something was wrong.
The GPS showed he was in the Pacific Ocean.
The Wi-Fi was connected to “Andrey_AI_Lab_5GHz” and was giving him a cryptic message:

“no escape until the map is whole.”

He looked around. The mansion’s hallways stretched endlessly, twisted and changed.
One minute he was in a library filled with books on linear algebra and the sound of an owl,
the next — in a gym with a punching bag labeled “Bayes”.

And then it hit him: the map had glitched. Its pieces were distorted, scrambled.
He needed to assemble it like a puzzle to figure out how to escape.
Al Pacino’s voice suddenly echoed in his headphones — or maybe it was just in his mind:

"Inch by inch, play by play, until we're finished. We’re in hell right now, gentlemen. Believe me. But we can climb out. Every inch is a step up.”

Slava looked at the glass. It wasn’t just glass, it was his lucky glass, the one that always brought him good fortune. He felt his fingers tighten around the cold surface, his treasure once again in his hands.

— “It’s mine... my precious...” — he whispered, gripping the glass.
Slava cracked his knuckles and muttered:

"I’m gonna do what’s called a ‘dirty hack’." 
That was the only way out of this twisted mansion: break the rules.

He opened Jupyter.

On one of the desks, he found an old laptop with a task flashing on the screen:

❗ To restore the map, solve this:

You have a dataset that can only be used with gradient boosting — no neural networks, no fancy transformers.

But:
— Some parts of the data are missing or corrupted.
— It’s unclear how to handle these gaps efficiently.

Your task:
— Understand how to prepare and process this incomplete data;
— Train a gradient boosting model that still gives strong, reliable predictions;
— Piece together the fragments of the dataset... and of the map itself.

Slava looked at the glass again. It was cold and real, and it was all he needed. But the way out was only through solving this task. He grabbed the laptop, started typing, and plunged into the world of data, determined to find a way to put this puzzle together.

"I’m going to have to make the choice," he whispered to himself, recalling a familiar line from The Matrix. "The red pill or the blue pill?"

But there was no turning back now.


## Overview

In this task you will have to solve a standard problem on tabular data. However, the final solution must be obtained using the function **clf_train**.

## Metric

squared [RMSE](https://en.wikipedia.org/wiki/Root_mean_square_deviation) 
$$ SCORE = (\sum_{i=1}^{n}{(true_i - predict_i)^{2}}/n)^{1/4} $$
* **true** - real value of target
* **predict** - your predict
* **n** - length of target

## Restriction

You cannot change the code of the **clf_train** function. You can only use submissions produced by this function. This function takes the following s input: training and test datasets with the features preprocessed by you, weights of target for training, id column for generating the sample_submission.csv and function for inverting the target. 

## Data

* **train_tables.csv** - train dataset with 9 numeric features, 3 datetime features and target
* **test_tables.csv** - test dataset with 9 numeric features, 3 datetime features and id for submission
* **sample_submission.csv** -  example of submission file with id coluns and target column that needed to predict.


## Legend
## Стакан Славы. Часть 2

Сейф открылся с приятным щелчком, словно он знал, что Слава — не просто вор, а тот, кто пришёл за своим сокровищем.

Он достал свой стакан. Настоящий. Тёплый. Целый.  
На мгновение всё стало на свои места. «Вот оно», — подумал он.  
Но вдруг знакомый, тревожный голос системы безопасности особняка разнёсся по коридорам:

“А что, если я скажу тебе, что всё не так, как кажется?”

Слава покачал головой, отгоняя странную мысль, но зловещий вопрос всё ещё звучал в его голове.

Он достал телефон, чтобы вызвать такси — и понял, что что-то не так.  
GPS показывал, что он находится **в Тихом океане**.  
Wi-Fi был подключён к сети **“Andrey_AI_Lab_5GHz”** и выводил странное сообщение:

“no escape until the map is whole.”

Он оглянулся. Коридоры особняка тянулись бесконечно, извиваясь и меняясь.  
В одну минуту он стоял в библиотеке, полной книг по линейной алгебре, где где-то ухала сова,  
а в следующую — в спортзале с боксерской грушей с надписью **“Bayes”**.

И тут его осенило: **карта сломалась**. Её части были искажены и перепутаны.  
Ему нужно было собрать её как пазл, чтобы понять, как выбраться.

Голос Аль Пачино внезапно прозвучал в его наушниках — а может быть, только в его голове:

> "Inch by inch, play by play, until we're finished. We’re in hell right now, gentlemen. Believe me. But we can climb out. Every inch is a step up.”

Слава посмотрел на стакан.  
Это был не просто стакан — **его счастливый стакан**, тот самый, который всегда приносил удачу.  
Он сильнее сжал холодное стекло, вновь ощущая своё сокровище в руках.

— “It’s mine... my precious...” — прошептал он.

Слава размял пальцы и пробормотал:

“I’m gonna do what’s called a ‘dirty hack’.”

Это был единственный способ выбраться из этого перекошенного особняка: **нарушить правила**.

Он открыл **Jupyter**.

На одном из столов лежал старый ноутбук, на экране которого мигало задание:

❗ **Чтобы восстановить карту, реши задачу:**

У тебя есть датасет, который можно использовать **только с градиентным бустингом** — никаких нейронных сетей, никаких модных трансформеров.

Но:

— Некоторые части данных **пропущены или повреждены**.  
— Неясно, **как эффективно обрабатывать эти пропуски**.

Твоя задача:

— Понять, как подготовить и обработать эти неполные данные;  
— Обучить модель **градиентного бустинга**, которая всё равно будет давать сильные и надёжные предсказания;  
— Собрать фрагменты датасета… **и самой карты**.

Слава снова посмотрел на стакан.  
Он был холодным и настоящим — и этого было достаточно.

Но выход был только один: **решить задачу**.

Он взял ноутбук, начал печатать и погрузился в мир данных, решив во что бы то ни стало собрать этот пазл.

“I’m going to have to make the choice,” — прошептал он, вспоминая знакомую фразу из *The Matrix*.  
“The red pill or the blue pill?”

Но пути назад уже не было.

---

## Условие

В этой задаче вам нужно решить стандартную задачу на **табличных данных**.  
Однако финальное решение должно быть получено с использованием функции **clf_train**.

---

## Метрика

Квадратичная ошибка **[RMSE](https://en.wikipedia.org/wiki/Root_mean_square_deviation)**

$$
SCORE = (\sum_{i=1}^{n}{(true_i - predict_i)^{2}}/n)^{1/4}
$$

* **true** — реальное значение таргета  
* **predict** — ваше предсказание  
* **n** — длина таргета  

---

## Ограничение

Вы **не можете изменять код функции `clf_train`**.  
Можно использовать только submission-файлы, созданные этой функцией.

Функция принимает на вход:

- обучающий и тестовый датасеты с **предобработанными вами признаками**  
- **веса таргета** для обучения  
- колонку **id** для генерации `sample_submission.csv`  
- функцию **обратного преобразования таргета**

---

## Данные

* **train_tables.csv** — обучающий датасет с **9 числовыми признаками**, **3 datetime признаками** и таргетом  
* **test_tables.csv** — тестовый датасет с **9 числовыми признаками**, **3 datetime признаками** и **id** для submission  
* **sample_submission.csv** — пример файла submission с колонками **id** и **target**, который нужно предсказать

read train and test dataframes

In [2]:
train = pd.read_csv('/kaggle/input/neoai-2025-tricy-table-data//train_tables.csv')
test = pd.read_csv('/kaggle/input/neoai-2025-tricy-table-data/test_tables.csv')

In [3]:
train.corr()

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,day,hour,minute,target
feat_0,1.000000,0.691265,0.009336,0.978724,-0.533931,0.983117,0.989082,0.845606,0.415550,-0.357984,-0.109879,0.017003,0.689174
feat_1,0.691265,1.000000,0.007070,0.689852,-0.762670,0.689417,0.708891,0.295771,0.571854,-0.513490,-0.128646,0.013866,0.995801
feat_2,0.009336,0.007070,1.000000,0.003251,-0.010177,-0.000354,0.006579,0.005010,-0.004279,0.002366,-0.004957,0.003577,0.003277
feat_3,0.978724,0.689852,0.003251,1.000000,-0.506773,0.991064,0.987752,0.844713,0.422582,-0.355659,-0.096635,0.011844,0.691262
feat_4,-0.533931,-0.762670,-0.010177,-0.506773,1.000000,-0.509086,-0.543649,-0.177143,-0.209921,0.481937,-0.073525,-0.018737,-0.746410
feat_5,0.983117,0.689417,-0.000354,0.991064,-0.509086,1.000000,0.992603,0.845360,0.423637,-0.352311,-0.098743,0.007663,0.691094
feat_6,0.989082,0.708891,0.006579,0.987752,-0.543649,0.992603,1.000000,0.833489,0.405698,-0.361915,-0.098225,0.004359,0.706916
feat_7,0.845606,0.295771,0.005010,0.844713,-0.177143,0.845360,0.833489,1.000000,0.298507,-0.142176,-0.048205,0.011097,0.301324
feat_8,0.415550,0.571854,-0.004279,0.422582,-0.209921,0.423637,0.405698,0.298507,1.000000,-0.280510,-0.114330,0.017087,0.623077
day,-0.357984,-0.513490,0.002366,-0.355659,0.481937,-0.352311,-0.361915,-0.142176,-0.280510,1.000000,-0.539579,-0.032738,-0.521932
hour,-0.109879,-0.128646,-0.004957,-0.096635,-0.073525,-0.098743,-0.098225,-0.048205,-0.114330,-0.539579,1.000000,-0.018502,-0.121372
minute,0.017003,0.013866,0.003577,0.011844,-0.018737,0.007663,0.004359,0.011097,0.017087,-0.032738,-0.018502,1.000000,0.018026
target,0.689174,0.995801,0.003277,0.691262,-0.746410,0.691094,0.706916,0.301324,0.623077,-0.521932,-0.121372,0.018026,1.000000

In [4]:
#sns.pairplot(train)

Исходя из графиков и расчетов сделаю вывод о том, что между фичами и таргетм существуют закномерности:
0 3 5 6 - коррелирует все между собой линейно
1 - имеет зависимость с 0 3 5 6 тремя линиями (древа)

In [5]:
xgb_imputer_linear = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.9,
    colsample_bytree=0.9,
    objective='reg:squarederror',
    random_state=42,
    n_jobs=-1,
)

imputer = IterativeImputer(estimator=xgb_imputer_linear, random_state=42)
train[['feat_5', 'feat_6']] = imputer.fit_transform(train[['feat_5', 'feat_6']])
test[['feat_5', 'feat_6']] = imputer.transform(test[['feat_5', 'feat_6']])

imputer = IterativeImputer(estimator=xgb_imputer_linear, random_state=42)
train[['feat_0', 'feat_6']] = imputer.fit_transform(train[['feat_0', 'feat_6']])
test[['feat_0', 'feat_6']] = imputer.transform(test[['feat_0', 'feat_6']])

imputer = IterativeImputer(estimator=xgb_imputer_linear, random_state=42)
train[['feat_3', 'feat_5']] = imputer.fit_transform(train[['feat_3', 'feat_5']])
test[['feat_3', 'feat_5']] = imputer.transform(test[['feat_3', 'feat_5']])

/usr/local/lib/python3.11/dist-packages/sklearn/impute/_iterative.py:785: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [6]:
xgb_imputer_tree = XGBRegressor(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=5,
    subsample=0.9,
    colsample_bytree=0.9,
    objective='reg:squarederror',
    random_state=42,
    n_jobs=-1,
)

imputer = IterativeImputer(estimator=xgb_imputer_tree, random_state=42)
train[['feat_1', 'feat_0', 'feat_3', 'feat_5', 'feat_6']] = imputer.fit_transform(train[['feat_1', 'feat_0', 'feat_3', 'feat_5', 'feat_6']])
test[['feat_1', 'feat_0', 'feat_3', 'feat_5', 'feat_6']] = imputer.transform(test[['feat_1', 'feat_0', 'feat_3', 'feat_5', 'feat_6']])

In [7]:
imputer = IterativeImputer(estimator=xgb_imputer_linear, random_state=42)
train[['feat_7', 'feat_0', 'feat_3', 'feat_5', 'feat_6']] = imputer.fit_transform(train[['feat_7', 'feat_0', 'feat_3', 'feat_5', 'feat_6']])
test[['feat_7', 'feat_0', 'feat_3', 'feat_5', 'feat_6']] = imputer.transform(test[['feat_7', 'feat_0', 'feat_3', 'feat_5', 'feat_6']])

In [8]:
imputer = IterativeImputer(estimator=xgb_imputer_tree, random_state=42)
train[['feat_8', 'feat_0', 'feat_3', 'feat_5', 'feat_6']] = imputer.fit_transform(train[['feat_8', 'feat_0', 'feat_3', 'feat_5', 'feat_6']])
test[['feat_8', 'feat_0', 'feat_3', 'feat_5', 'feat_6']] = imputer.transform(test[['feat_8', 'feat_0', 'feat_3', 'feat_5', 'feat_6']])

In [9]:
median_two = train[train.feat_2.notnull()].feat_2.mean()
train.iloc[train.feat_2.isna(), 2] = median_two
test.iloc[test.feat_2.isna(), 2]  = median_two

median_four = train[train.feat_4.notnull()].feat_4.mean()
train.iloc[train.feat_4.isna(), 4] = median_four
test.iloc[test.feat_4.isna(), 4] = median_four

In [10]:
minute = train[train.minute.notnull()].minute.mean()
hour = train[train.hour.notnull()].hour.median()
day = train[train.day.notnull()].day.mode().values[0]

train.iloc[train.day.isna(), 9] = day
test.iloc[test.day.isna(), 9] = day

train.iloc[train.hour.isna(), 10] = hour
test.iloc[test.hour.isna(), 10] = hour

train.iloc[train.minute.isna(), 11] = minute
test.iloc[test.minute.isna(), 11] = minute

Inference function

**You cannot change this function.**

**Вы не можете менять код этой функции.**

In [11]:
def clf_train(train, test, target, weight_col, id_col, name_file='sub.csv', func_inv=None):

    xgb_params = {
        'n_estimators': 1400,
        'learning_rate': 0.02,
        'max_depth': 6,
        'min_child_weight': 2,
        'subsample': 0.9,
        'colsample_bytree': 0.9,
        'reg_alpha': 0.1,
        'reg_lambda': 1.5,
        'objective': 'reg:absoluteerror',
        'tree_method': 'hist',
        'n_jobs': -1,
    }

    predict_test = np.zeros(len(test))
    for rs in [42, 52, 62]:
        model = XGBRegressor(**xgb_params, random_state=rs)
        model.fit(train, target, sample_weight=weight_col)
        predict_test += model.predict(test) / 3

    if func_inv:
        predict_test = func_inv(predict_test)

    sub = pd.DataFrame()
    sub['id'] = id_col
    sub['target'] = predict_test
    sub.to_csv(name_file, index=None)
    return sub

Function to change target if you need it

In [12]:
def func_inv(x):
    return np.exp(x)

ids = test['id'].tolist()

X = train.drop(columns='target')
y = train.target

Train and inference. 
You should use **clf_train** for generating submission

Вы должны использовать  **clf_train** для генерации файла с решением

In [13]:
drop_cols = ['target']
train_cols = [c for c in train.columns if c not in drop_cols]
weight = np.ones(len(train))
arg1 = pd.concat([X, np.log(y)], axis=1)[train_cols]
arg2 = test[train_cols]
arg3 = np.log(y)

test_sub = clf_train(arg1, arg2, arg3, weight, ids, name_file='submission_xgb3.csv', func_inv=func_inv)
test_sub

          id      target
0          0  721.055688
1          1  703.474385
2          2  835.788569
3          3  703.005928
4          4  698.883634
...      ...         ...
22373  22373  299.510225
22374  22374  681.452417
22375  22375  706.750376
22376  22376  683.844603
22377  22377  731.576802

[22378 rows x 2 columns]

In [14]:
test

,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,day,hour,minute,id
0,457.008442,2600.604492,20.181569,84.596243,2856.659366,50.060753,2544.418381,1325.720947,644.240441,1.0,18.0,43.0,0
1,446.657066,2533.300979,20.436051,84.450941,2897.636139,49.893098,2507.359961,1322.860255,650.385119,2.0,1.0,49.0,1
2,523.784254,2945.959678,20.251782,86.819573,2874.224897,52.950622,2928.299439,1371.959717,649.844113,1.0,4.0,2.0,2
3,441.081405,2550.833526,20.288787,84.005320,2874.224897,49.673206,2507.625488,1318.855760,647.504883,2.0,2.0,14.0,3
4,442.619995,2574.342039,20.479995,83.448487,2878.257006,49.108300,2518.966718,1306.454903,642.635453,2.0,6.0,33.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22373,907.955248,1569.045667,20.316368,114.855305,2929.574401,80.848639,6012.199365,4520.122425,571.206335,2.0,14.0,25.0,22373
22374,423.103414,2488.001106,20.471186,84.758630,2898.564693,49.635579,2463.441421,1321.615195,645.331571,1.0,9.0,41.0,22374
22375,450.127577,2572.825749,20.341831,83.814283,2853.669534,49.271981,2507.645829,1319.358398,649.490836,2.0,10.0,40.0,22375
22376,444.697150,2505.655352,20.359834,83.681038,2865.378379,49.155401,2460.312849,1306.052577,654.740656,1.0,10.0,24.0,22376
22377,430.922812,2648.718893,20.136339,84.991266,2874.224897,51.258389,2591.351496,1325.423675,643.632310,1.0,10.0,8.0,22377